### ISSUE TITLE
Selection highlight in search very low contrast

### ISSUE THREAD

**Issue by joshclow** [mintchipleaf/fairyfloss-vscode#1]
In the search pane, the selection highlight in the search field is *extremely* close to the background color. It’s not quickly obvious to me why, because it looks fine in the extensions search. I’ll poke around a bit and see if I can figure it out

**Comment by joshclow** [comment]
I see. The problem is that `selection.background` is blended with the background (even if the alpha channel is explicitly set to #ff), so the color for this case needs to be lightened so that the effective contrast ratio is higher. I'll dink around some more and see if I can't find a better color that stays in the fairyfloss palette

**Comment by mintchipleaf** [comment]
Thank you so much for looking into this! This particular color issue has been a thorn in my side since day 1 (and the only location I know where vscode blends like that.) Looks like #c0bdd1, used as foreground color in several places, should work just fine!
